-- A dietitian's client. Tenant-owned: every row belongs to exactly one practitioner,
-- and every query against this table is scoped by practitioner_id.
CREATE TABLE client (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practitioner_id BIGINT       NOT NULL REFERENCES practitioner (id),
    full_name       VARCHAR(160) NOT NULL,
    email           CITEXT,
    phone           VARCHAR(40),
    date_of_birth   DATE,
    goal            VARCHAR(500),
    notes           TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT       NOT NULL DEFAULT 0
);

-- Every read is scoped by practitioner, so the tenant column leads every index.
CREATE INDEX client_practitioner_idx ON client (practitioner_id);
CREATE INDEX client_practitioner_name_idx ON client (practitioner_id, full_name);
