-- The food catalogue is a shared table with per-practitioner overlays, which makes it the
-- one table in the system that is neither wholly global nor wholly tenant-owned.
--
-- A row is one of three things:
--   global      practitioner_id IS NULL,     overrides_food_id IS NULL
--   custom      practitioner_id = X,          overrides_food_id IS NULL
--   override    practitioner_id = X,          overrides_food_id = <a global food>
--
-- An override is copy-on-write: it carries a complete set of values rather than a sparse diff,
-- so every row is self-describing and reading the catalogue needs no COALESCE across tables.
CREATE TABLE food (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practitioner_id   BIGINT       REFERENCES practitioner (id),
    overrides_food_id BIGINT       REFERENCES food (id) ON DELETE CASCADE,

    name_el           VARCHAR(200) NOT NULL,
    name_en           VARCHAR(200),
    category          VARCHAR(20)  NOT NULL,

    -- Macros live on the row, not in a nutrient table: they are read on every keystroke in
    -- the plan builder. Micronutrients will go in a separate table for the opposite reason.
    energy_kcal       NUMERIC(8, 2) NOT NULL,
    protein_g         NUMERIC(8, 2) NOT NULL,
    carbohydrate_g    NUMERIC(8, 2) NOT NULL,
    fat_g             NUMERIC(8, 2) NOT NULL,

    -- Provenance per row. If a source later proves unusable, its rows can be identified and
    -- removed without auditing the whole catalogue.
    source            VARCHAR(40)  NOT NULL,

    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ,
    version           BIGINT       NOT NULL DEFAULT 0,

    -- An override must belong to somebody. A global row cannot override anything.
    CONSTRAINT food_override_has_owner
        CHECK (overrides_food_id IS NULL OR practitioner_id IS NOT NULL)
);

-- One override per practitioner per global food. Without this a practitioner could end up with
-- two competing versions of the same food and no defined winner.
CREATE UNIQUE INDEX food_override_uq
    ON food (practitioner_id, overrides_food_id)
    WHERE overrides_food_id IS NOT NULL;

CREATE INDEX food_global_idx ON food (category) WHERE practitioner_id IS NULL;
CREATE INDEX food_practitioner_idx ON food (practitioner_id) WHERE practitioner_id IS NOT NULL;
CREATE INDEX food_name_el_idx ON food (lower(name_el));

-- Practitioners work in natural units — one egg, three crackers, a slice — not grams.
-- Without portions the builder either forces gram entry or hardcodes conversions.
CREATE TABLE food_portion (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id    BIGINT        NOT NULL REFERENCES food (id) ON DELETE CASCADE,
    label_el   VARCHAR(80)   NOT NULL,
    grams      NUMERIC(8, 2) NOT NULL CHECK (grams > 0),
    is_default BOOLEAN       NOT NULL DEFAULT FALSE,
    sort_order INT           NOT NULL DEFAULT 0
);

CREATE INDEX food_portion_food_idx ON food_portion (food_id);

-- A proposed change to the shared catalogue, distinct from a private override. Overriding is
-- immediate and affects only the practitioner who did it; suggesting asks for the default
-- itself to change and waits for review.
CREATE TABLE food_suggestion (
    id                     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_id                BIGINT        NOT NULL REFERENCES food (id) ON DELETE CASCADE,
    practitioner_id        BIGINT        NOT NULL REFERENCES practitioner (id),

    proposed_name_el       VARCHAR(200),
    proposed_energy_kcal   NUMERIC(8, 2),
    proposed_protein_g     NUMERIC(8, 2),
    proposed_carbohydrate_g NUMERIC(8, 2),
    proposed_fat_g         NUMERIC(8, 2),
    rationale              TEXT,

    status                 VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    reviewed_at            TIMESTAMPTZ,

    CONSTRAINT food_suggestion_status
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED'))
);

CREATE INDEX food_suggestion_status_idx ON food_suggestion (status);
CREATE INDEX food_suggestion_practitioner_idx ON food_suggestion (practitioner_id);
