-- A diet plan: the deliverable the whole product exists to produce.
--
-- plan -> plan_day -> plan_meal -> plan_item, four levels deep. A week-long plan is roughly
-- 7 days x 5 meals x 4 items, so reads of this aggregate are the hottest path in the system
-- and the easiest place to write an accidental N+1.
CREATE TABLE plan (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practitioner_id       BIGINT        NOT NULL REFERENCES practitioner (id),
    client_id             BIGINT        NOT NULL REFERENCES client (id) ON DELETE CASCADE,

    name                  VARCHAR(200)  NOT NULL,
    status                VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',

    -- Targets are copied onto the plan rather than recomputed on read. The practitioner may
    -- have arrived at them by any of the nutrition module's routes, and the plan has to keep
    -- meaning the same thing tomorrow.
    target_kcal           NUMERIC(8, 2) NOT NULL,
    target_protein_g      NUMERIC(8, 2) NOT NULL,
    target_carbohydrate_g NUMERIC(8, 2) NOT NULL,
    target_fat_g          NUMERIC(8, 2) NOT NULL,
    basis                 VARCHAR(40),
    activity_factor       NUMERIC(4, 3),

    notes                 TEXT,

    created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ,
    version               BIGINT        NOT NULL DEFAULT 0,

    CONSTRAINT plan_status CHECK (status IN ('DRAFT', 'ISSUED', 'ARCHIVED'))
);

CREATE INDEX plan_practitioner_idx ON plan (practitioner_id);
CREATE INDEX plan_client_idx ON plan (client_id);

CREATE TABLE plan_day (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id        BIGINT       NOT NULL REFERENCES plan (id) ON DELETE CASCADE,
    day_index      INT          NOT NULL,
    -- Practitioners relabel days as "Επιλογή 1" rather than "Δευτέρα" when the plan is a set
    -- of interchangeable options rather than a literal week.
    label_override VARCHAR(80),
    CONSTRAINT plan_day_uq UNIQUE (plan_id, day_index)
);

CREATE INDEX plan_day_plan_idx ON plan_day (plan_id);

CREATE TABLE plan_meal (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_day_id BIGINT      NOT NULL REFERENCES plan_day (id) ON DELETE CASCADE,
    meal_type   VARCHAR(24) NOT NULL,
    time_label  VARCHAR(40),
    sort_order  INT         NOT NULL DEFAULT 0
);

CREATE INDEX plan_meal_day_idx ON plan_meal (plan_day_id);

-- An item records what was prescribed, not a pointer to what the food currently says.
--
-- The food name, portion label, portion weight and all four macro figures are snapshotted at
-- the moment the item is added. An issued plan is a clinical document: correcting the catalogue
-- next month must not silently alter what a client was told to eat last month, and a printed
-- PDF must always match what the system shows.
--
-- food_id is kept as a soft reference and set null if the food is deleted, so a practitioner
-- removing one of their custom foods cannot destroy the plans that used it.
CREATE TABLE plan_item (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_meal_id   BIGINT        NOT NULL REFERENCES plan_meal (id) ON DELETE CASCADE,
    food_id        BIGINT        REFERENCES food (id) ON DELETE SET NULL,

    food_name      VARCHAR(200)  NOT NULL,
    name_override  VARCHAR(200),
    portion_label  VARCHAR(80)   NOT NULL,
    portion_grams  NUMERIC(8, 2) NOT NULL,
    quantity       NUMERIC(8, 3) NOT NULL CHECK (quantity > 0),

    -- The composition as it stood when the item was added. This is the real snapshot:
    -- the absolute figures below are a pure function of these, the portion weight and the
    -- quantity, so changing an amount recomputes exactly rather than rescaling an already
    -- rounded number and accumulating drift.
    energy_per_100g       NUMERIC(10, 3) NOT NULL,
    protein_per_100g      NUMERIC(10, 3) NOT NULL,
    carbohydrate_per_100g NUMERIC(10, 3) NOT NULL,
    fat_per_100g          NUMERIC(10, 3) NOT NULL,

    -- Derived, stored so totals can be aggregated in SQL without recomputing.
    energy_kcal    NUMERIC(10, 3) NOT NULL,
    protein_g      NUMERIC(10, 3) NOT NULL,
    carbohydrate_g NUMERIC(10, 3) NOT NULL,
    fat_g          NUMERIC(10, 3) NOT NULL,

    sort_order     INT           NOT NULL DEFAULT 0
);

CREATE INDEX plan_item_meal_idx ON plan_item (plan_meal_id);
