-- What can be measured, as reference data rather than as columns.
--
-- Columns would mean a migration for every new marker, and Phase 1 adds skinfolds,
-- circumferences and blood markers. A type table costs one join and absorbs all of them.
CREATE TABLE measurement_type (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(40)   NOT NULL UNIQUE,
    label_el      VARCHAR(80)   NOT NULL,
    label_en      VARCHAR(80)   NOT NULL,
    unit          VARCHAR(16)   NOT NULL,
    category      VARCHAR(24)   NOT NULL,

    -- Optional healthy range. Null for anthropometrics, where there is no single right answer.
    -- Present for the blood markers Phase 1 adds, which is where in/out-of-range flags matter.
    reference_min NUMERIC(10, 3),
    reference_max NUMERIC(10, 3),

    decimals      INT           NOT NULL DEFAULT 1,
    sort_order    INT           NOT NULL DEFAULT 0,

    CONSTRAINT measurement_type_category CHECK (category IN
        ('ANTHROPOMETRIC', 'BODY_COMPOSITION', 'CIRCUMFERENCE', 'SKINFOLD', 'BLOOD_MARKER'))
);

-- A recorded value.
--
-- practitioner_id is carried here as well as on the client so that every read is scoped by
-- tenant without a join, matching how every other tenant-owned table behaves.
CREATE TABLE measurement (
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practitioner_id     BIGINT         NOT NULL REFERENCES practitioner (id),
    client_id           BIGINT         NOT NULL REFERENCES client (id) ON DELETE CASCADE,
    measurement_type_id BIGINT         NOT NULL REFERENCES measurement_type (id),

    value               NUMERIC(10, 3) NOT NULL,
    recorded_on         DATE           NOT NULL,
    notes               VARCHAR(500),

    created_at          TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT         NOT NULL DEFAULT 0,

    -- One value per client per type per day. Recording a weight twice on the same date is a
    -- correction, not a second data point, and without this the change series has no defined
    -- order within a day.
    CONSTRAINT measurement_uq UNIQUE (client_id, measurement_type_id, recorded_on)
);

CREATE INDEX measurement_practitioner_idx ON measurement (practitioner_id);
-- Leads with the columns every series query filters on, in the order it reads them.
CREATE INDEX measurement_series_idx ON measurement (client_id, measurement_type_id, recorded_on);

INSERT INTO measurement_type (code, label_el, label_en, unit, category, decimals, sort_order) VALUES
('WEIGHT',           'Βάρος',              'Weight',            'kg',    'ANTHROPOMETRIC',   1, 10),
('HEIGHT',           'Ύψος',               'Height',            'cm',    'ANTHROPOMETRIC',   1, 20),

('BODY_FAT_PCT',     'Λιπώδης μάζα',       'Body fat',          '%',     'BODY_COMPOSITION', 1, 30),
('MUSCLE_MASS',      'Μυϊκή μάζα',         'Muscle mass',       'kg',    'BODY_COMPOSITION', 1, 40),
('BODY_WATER_PCT',   'Ολικό νερό σώματος', 'Body water',        '%',     'BODY_COMPOSITION', 1, 50),
('BONE_MASS',        'Οστική μάζα',        'Bone mass',         'kg',    'BODY_COMPOSITION', 2, 60),
('VISCERAL_FAT',     'Σπλαχνικό λίπος',    'Visceral fat',      'level', 'BODY_COMPOSITION', 0, 70),
('BMR_MEASURED',     'Βασικός μεταβολισμός','Measured BMR',     'kcal',  'BODY_COMPOSITION', 0, 80),

('WAIST',            'Περίμετρος μέσης',   'Waist',             'cm',    'CIRCUMFERENCE',    1, 90),
('HIP',              'Περίμετρος γοφών',   'Hip',               'cm',    'CIRCUMFERENCE',    1, 100),
('CHEST',            'Περίμετρος στήθους', 'Chest',             'cm',    'CIRCUMFERENCE',    1, 110),
('ARM',              'Περίμετρος βραχίονα','Arm',               'cm',    'CIRCUMFERENCE',    1, 120),
('THIGH',            'Περίμετρος μηρού',   'Thigh',             'cm',    'CIRCUMFERENCE',    1, 130),
('NECK',             'Περίμετρος λαιμού',  'Neck',              'cm',    'CIRCUMFERENCE',    1, 140);
