-- The record of what was said in a consultation.
--
-- Small in structure and the most sensitive free text in the system: these are clinical notes
-- about a named person, squarely within GDPR Article 9. Nothing here is shown to the client.
CREATE TABLE journal_entry (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practitioner_id BIGINT       NOT NULL REFERENCES practitioner (id),
    client_id       BIGINT       NOT NULL REFERENCES client (id) ON DELETE CASCADE,

    -- Separate from created_at because sessions are frequently written up afterwards, and the
    -- date that matters clinically is when the consultation happened.
    entry_date      DATE         NOT NULL,

    title           VARCHAR(200),
    content         TEXT         NOT NULL,

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX journal_entry_practitioner_idx ON journal_entry (practitioner_id);
-- Entries are read newest-first for one client, which is exactly this index.
CREATE INDEX journal_entry_client_date_idx ON journal_entry (client_id, entry_date DESC);
