-- Who read or changed which client record.
--
-- Distinct from the HTTP request log, which is operational, unstructured and kept only as long
-- as the log sink retains it. This is a queryable record with its own retention, and it is what
-- answers "whose data was accessed" after a suspected breach — an obligation under GDPR Article
-- 33/34 that infrastructure audit logs do not discharge, because they see a request to a URL and
-- not a practitioner reading a named person's clinical notes.
CREATE TABLE audit_log (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    practitioner_id BIGINT      NOT NULL REFERENCES practitioner (id),

    -- Not a foreign key. The audit trail must outlive the record it describes: erasing a client
    -- must not erase the evidence of who looked at them.
    client_id       BIGINT,

    action          VARCHAR(32) NOT NULL,
    entity_type     VARCHAR(32) NOT NULL,
    entity_id       BIGINT,

    correlation_id  VARCHAR(64),
    ip_address      VARCHAR(45),
    occurred_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT audit_log_action CHECK (action IN ('READ', 'CREATE', 'UPDATE', 'DELETE', 'EXPORT'))
);

CREATE INDEX audit_log_practitioner_idx ON audit_log (practitioner_id, occurred_at DESC);
CREATE INDEX audit_log_client_idx ON audit_log (client_id, occurred_at DESC);
